### ISSUE TITLE
Add an example for transitionBuilder

### ISSUE THREAD

**Issue by Faiyyaz** [drogel/keyboard_attachable#6]
Hey,

Thanks for the great library. Can you just add an example on how to use transitionBuilder, because currently i am trying to but it hides my ui instead of showing the beginning.

I used this for transitionBuilder

```
transitionBuilder: (
          Widget child,
          Animation<double> animation,
          double keyboardHeight,
        ) {
          return FadeTransition(
            child: child,
            opacity: animation,
          );
        },
```

**Comment by drogel** [comment]
Thank you for taking the time for this suggestion. Now that I am taking a look at it, I see what you mean and I agree with you: the transition builder needs to be explained in more detail.

I will add an example that makes use of the transition builder, and I will extend the documentation to further explain what the `animation` parameter does under the hood. In the meantime, here is a quick explanation that will hopefully unblock your current issue.

Keep in mind that the `animation.value` of the transition builder will be 0 when the keyboard is dismissed, and 1 when the keyboard is shown. That means that, in your case, the `opacity` is 0 (invisible) when the keyboard is hidden and 1 (visible) when shown. If you want the opposite scenario, you need to reverse those values. That can be done by replacing the `animation` parameter in your `FadeTransition` by `Tween<double>(begin: 1, end: 0).animate(animation)`. This way, the animation value will be 1 in the beginning (hidden keyboard) and 0 in the end (shown keyboard).

Here is a full example of a widget that is showing when the keyboard is hidden, and hiding when the keyboard is shown:

```dart
import 'package:flutter/material.dart';
import 'package:keyboard_attachable/keyboard_attachable.dart';

void main() => runApp(Example());

class Example extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Keyboard Attachable Demo',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(primarySwatch: Colors.blue),
        home: KeyboardAttachablePage(),
      );
}

/// Builds a [Scaffold] that lays out a footer at the bottom of the page.
class KeyboardAttachablePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        resizeToAvoidBottomInset: false,
        appBar: AppBar(title: const Text("Keyboard Attachable demo")),
        body: FooterLayout(
          footer: KeyboardAttachableFooter(),
          child: ColorsList(),
        ),
      );
}

/// Builds a footer that animates its bottom space when the keyboard is shown.
class KeyboardAttachableFooter extends StatelessWidget {
  @override
  Widget build(BuildContext context) => KeyboardAttachable(
        backgroundColor: Colors.blue,
        keyboardTransitionBuilder: (child, animation) => Column(
          children: <Widget>[
            child,
            SizeTransition(
              sizeFactor: Tween<double>(begin: 1, end: 0).animate(animation),
              child: Container(
                height: 100,
                child: Center(
                  child: FadeTransition(
                    opacity: Tween<double>(begin: 1, end: 0).animate(animation),
                    child: Text(
                      "I am afraid of the keyboard!",
                      style: Theme.of(context).textTheme.headline5,
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
        child: Container(
          padding: const EdgeInsets.all(16),
          color: Colors.blue,
          child: TextField(
            decoration: InputDecoration(
              hintText: "Tap me!",
              fillColor: Colors.white,
              filled: true,
              border: const OutlineInputBorder(),
            ),
          ),
        ),
      );
}

/// Builds a [ListView] made of colored containers that fill the page.
class ColorsList extends StatelessWidget {
  @override
  Widget build(BuildContext context) => ListView.builder(
        itemExtent: 66,
        itemCount: Colors.primaries.length,
        itemBuilder: (_, i) => Container(
          color: Colors.primaries[i].withOpacity(0.2),
        ),
      );
}
```

And here is what it looks like.

![keyboard_attachable](https://user-images.githubusercontent.com/50502687/84630400-29802400-aeec-11ea-8472-94ca180742f6.gif)

Hope that was helpful, I will be adding a similar example to the project. Thanks a lot for the suggestion!

**Comment by Faiyyaz** [comment]
Thanks for the update 😉

No issue happy to help!

**Comment by Faiyyaz** [comment]
Hey my use case is little different. 
Actually i feel a jump on iOS simulator so i want to maybe somehow slow the jump or animated it for that i wanted to use transitionBuilder but as i can see you have different use case in mind

**Comment by drogel** [comment]
I see, what is the use case you are trying to implement? Under which conditions you are experiencing that jump?

I suspect the jump might be caused by a widget whose height is not being resized in sync with the keyboard animation. That is the reason why I used a `SizeTransition` in my example. Another reason might be that you are using a bottom `SafeArea` widget or you forgot to set your `Scaffold`'s `resizeToAvoidBottomInset` parameter to `false`. 

I would suggest you to check if any of the above conditions apply to your case. Let me know if there is anything I can do to help you with that issue.

**Comment by Faiyyaz** [comment]
My use case is a sample chat screen like facebook, instagram and i want the textfield to float with keyboard which is working fine but i have found some glitch in the transition. Attaching the gif for the same

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18116236/84649256-d2964100-af23-11ea-80d0-e0d7fa5f5482.gif)

**Comment by drogel** [comment]
Okay, I see. Two ideas come to mind:

- For heavy (and not so heavy) UI configurations, animations can be janky in Flutter debug mode, when running on simulators etc. I myself have experienced delays with the soft keyboard in iOS simulators when developing the package, but in release mode on real devices the sync was fine. Do you experience the same issue when running on a real device in release mode?
- Are you using `SafeArea` or `MediaQuery.of(context).padding.bottom` in that screen? The bottom insets that the framework adds for the safe area can jump from 0 to a non-zero value (without an animation) when the keyboard is shown and hidden, and that is out of the control of the package, since it is provided by the framework. That can also cause unexpected jumps.

Kindly review the above comments and see if that helps. If you could provide a minimal example to reproduce the issue, that would be very helpful for me if you need further assistance.

**Comment by Faiyyaz** [comment]
For the first question, no I haven't tried in the real device. I can try and let you know the behaviour later in sometime.

And for the second question no i am not using safeArea and bottom padding.

**Comment by Faiyyaz** [comment]
Hey just a note you need to remove the keyboard visibility dependency and make it androidX and use because on android your plugin will give the following issue

```
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':keyboard_visibility:verifyReleaseResources'.                                           
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade                  
   > Android resource linking failed                                                                               
     /Users/faiyyazkhatri/.gradle/caches/transforms-2/files-2.1/b011d4b5d2ec7eea4ff52e346e1e6e65/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                                                                   
     /Users/faiyyazkhatri/.gradle/caches/transforms-2/files-2.1/b011d4b5d2ec7eea4ff52e346e1e6e65/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.
                                                                                                                   
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 2m 8s      
```

**Comment by drogel** [comment]
Pull request merged, I was not aware about that AndroidX issue from the original keyboard visibility package. Thanks a lot for pointing that out!

I am working on an update of the keyboard_attachable package that includes an example of the transition builder, and I will publish that together with your fix as a version 1.0.2 of the package.

By the way, are there any updates on the animation issue you experienced in your chat app?

Thanks a lot.

**Comment by Faiyyaz** [comment]
Sorry,

I was busy in setting up the chat actually i will surely let you know around same time tomorrow.

**Comment by drogel** [comment]
Don't worry! No need to rush :-)

Just wanted to give you a quick update: I cannot publish the new version 1.0.2 of the keyboard attachable package, because the fixed version of the keyboard visibility package points to a git repository now, and not to a published package in pub.dev (pub.dev does not allow that). This means that we need the original keyboard visibility package updated and published with the fix, or a different package for the keyboard visibility notifications functionality.

In the meantime, I will upload an updated version of keyboard_attachable with the transition example, and you can fork the project so that the keyboard visibility points to your git repository fork. That way the AndroidX issue can be solved for your project until we have a solution that complies with pub.dev rules :-) Thanks!

**Comment by Faiyyaz** [comment]
Yes actually i had made a PR request long back in that original repository but i think the owner is not active these days. Maybe we should do one thing i will publish the keyboard visibility as a package to pub.dev and then you can add that and push your code to pub.dev

**Comment by drogel** [comment]
Sounds good!

**Comment by Faiyyaz** [comment]
Hey can you guide me how to upload package to pub.dev because i am unable to create publisher. It is asking me for domain name and i don't have any.

**Comment by drogel** [comment]
Yeah, that is required for verified publishers, but you don't need to be a verified publisher to publish a package. For example, I am not a verified publisher and I have published three Flutter packages. It has some advantages though, but it's not mandatory. You can read more about verified publishers [in this dart.dev article](https://dart.dev/tools/pub/verified-publishers).

If you want to publish the package as an unverified publisher, all you need is a Google account. You can follow the steps described in [this flutter.dev article](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#publish), in the section "Publishing your package". In summary, all you need to do is make sure your documentation, LICENSE, CHANGELOG, and README are in place, and then run the `$ flutter pub publish` command, solving any warnings that might occur.

**Comment by Faiyyaz** [comment]
Okay i will do it this weekend.... Actually i need to pull and change package name too otherwise they will rejected the package... And currently i don't have much spare time... I will let you know once done... Hopefully by this weekend!

**Comment by drogel** [comment]
Yes, pub.dev needs to identify packages univocally, so every package has to have it's own unique name.

Don't worry! No need to rush, just let me know when it's ready and I will update the dependencies. If you need the AndroidX fix for your projects, you can always depend on your forked version of the package, so it's all good :-) Thanks a lot!

**Comment by Faiyyaz** [comment]
Yes for now i have done that only. I had forked yours and change the dependency to mine and using it!

**Comment by Faiyyaz** [comment]
Hey i am getting this error on android after cloning the keyboard_visibility package and trying to make it my own

```
/flutter ( 7745): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter ( 7745): The following PlatformException was thrown while activating platform stream on channel keyboard:
I/flutter ( 7745): PlatformException(error, Parameter specified as non-null is null: method
I/flutter ( 7745): kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter arguments, null)
I/flutter ( 7745): 
I/flutter ( 7745): When the exception was thrown, this was the stack:
I/flutter ( 7745): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter ( 7745): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
I/flutter ( 7745): <asynchronous suspension>
I/flutter ( 7745): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter ( 7745): #3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
I/flutter ( 7745): #4      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:505:64)
I/flutter ( 7745): #9      new KeyboardVisibilityNotification (package:keyboard/keyboard.dart:37:10)
I/flutter ( 7745): #10     new _KeyboardVisibilityExampleState (package:keyboard_example/main.dart:31:11)
I/flutter ( 7745): #11     KeyboardVisibilityExample.createState (package:keyboard_example/main.dart:26:7)
I/flutter ( 7745): #12     new StatefulElement (package:flutter/src/widgets/framework.dart:4591:25)
I/flutter ( 7745): #13     StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:894:38)
I/flutter ( 7745): ...     Normal element mounting (115 frames)
I/flutter ( 7745): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter ( 7745): #129    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter ( 7745): ...     Normal element mounting (253 frames)
I/flutter ( 7745): #382    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter ( 7745): #383    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter ( 7745): #384    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
I/flutter ( 7745): #385    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
I/flutter ( 7745): #386    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
I/flutter ( 7745): #387    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter ( 7745): #388    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
I/flutter ( 7745): #389    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
I/flutter ( 7745): #390    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
I/flutter ( 7745): (elided 15 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter ( 7745): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by drogel** [comment]
To be honest, I don't know what that error means. It looks like the error is coming directly from Android, from the platform channel communication with the Flutter side, but since I have very little experience with Android frameworks, I don't know what might be causing it.

If the keyboard visibility package is causing issues, an alternative would be to abstract the visibility notifications away in keyboard_attachable, and depend on a different package for keyboard visibility notifications. There are plenty of solutions on pub.dev. For example [this one](https://pub.dev/packages/flutter_keyboard_visibility) looks like it is being actively mantained. That might be actually an easier solution. I will give it a thought for sure.

**Comment by Faiyyaz** [comment]
Okay i have seen that actually it is a fork of the same plugin which has been updated i will test in my android device right now and will let you know if its working and if its compatible with androidX

**Comment by Faiyyaz** [comment]
Hey added a PR request. Everything works fine now. Even release build is working fine. I tested on android device. Check once on iOS and maybe release a new version ASAP. Thanks for the support!

**Comment by drogel** [comment]
Hi, just letting you know that I just published the version 1.0.3 of the package, it should be publicly available. It includes the transition builder example from version 1.0.2 and the keyboard visibility dependency change with the Android X fix. Tested it on iOS and it was working fine too.

I am closing this issue now, thanks for your contribution and for the suggestion, very much appreciated!
